### ISSUE TITLE
"Standard" Filter

### ISSUE THREAD

**Issue by ibews** [Freezard/hs-collection-tracker#47]
I think (at least in the "Progress"-Tab) a filter to just show cards which would be included in the Standard-Mode at that time would be quite useful.
That way you could see your "Overall"-Progress, as well as your current Standard-Progress without having to compute the missing Dust/your progress percentage manually.

**Comment by Freezard** [comment]
Good idea, will be adding that.

**Comment by Freezard** [comment]
Fixed with latest update.
