### ISSUE TITLE
delete bug two goldens

### ISSUE THREAD

**Issue by Robricran** [Freezard/hs-collection-tracker#52]
Hi
Thanks for the tracker. I ran into an unusual bug. While working on the priest sheet I had a common card with two regular copies and two golden copies. When I clicked to mark the second golden the entire card disappeared from the list.  I recreated the bug with more than one card on that list. Can't figure out how to get it back, the undo all with right click does not work, so I have not tried with other cards to see how widespread the problem is. Please let me know if there is a fix for this issue.

**Comment by Freezard** [comment]
Click the "Show only missing cards" button on the filter bar. You probably had it on.

**Comment by Robricran** [comment]
Thanks for the reply. It worked. I did not realize that I had it on.
