### ISSUE TITLE
Wotog cards not shown in firefox

### ISSUE THREAD

**Issue by jakub-rezek** [Freezard/hs-collection-tracker#54]
Hi,
I cannot see cards from whispers of the old gods set in firefox. I tried to export to opera and import again to firefox. I even cleared cookies and localstorage but to no avail. Firefox still shows total count of 1394 cards instead of 1641.

Best regards Jakub Rezek

**Comment by Freezard** [comment]
That's weird. I just installed Firefox and I got all the cards. There's probably some problem with localStorage and it wasn't cleared correctly.

Go to the website and open the console (F12) and type "localStorage.clear()". Refresh and it should work.

**Comment by Leonix** [comment]
Could have been offline at the time of update. Failed to load cards from online database and used local version without WotOG.
