### ISSUE TITLE
Add deck recipes progress

### ISSUE THREAD

**Issue by Freezard** [Freezard/hs-collection-tracker#56]
Add progress for deck recipes, ie how many normal and golden cards you're missing for each recipe, and the dust required to craft them. Could use card images like the ones used in decks in-game. Most people won't care about it, but code could be used for custom decks later on.

**Comment by Leonix** [comment]
I very much like and support this idea. I use the tracker primarily to plan decks while I don't have access to Hearthstone client. (Don't care about deck images though.)

**Comment by Freezard** [comment]
I'm working on this right now. I've added a function that displays decks which will be used for the recipes, and can be used by other features when needed.
