### ISSUE TITLE
Import collections from HearthPwn

### ISSUE THREAD

**Issue by Freezard** [Freezard/hs-collection-tracker#57]
HearthPwn seems to be the best place to import collections from right now, as it's used by a lot of people and Innkeeper is the only way to import decks straight from the game that I know of. You could gather all data if a user makes their collection public, but not sure how well HTML parsers/regex is supported in JavaScript.

**Comment by Leonix** [comment]
HearthPwn saves cards collection to `localStorage.HearthCollection`. Should be able to fetch it with a simple bookmarklet, copy, and then import into tracker.

**Comment by Freezard** [comment]
It seems only normal cards are stored there, not golden. But might be better than nothing.

**Comment by Freezard** [comment]
I was just going to add this, but then I noticed that HearthCollection doesn't separate normal and golden cards, it just says count: x. So unfortunately it's not possible to use to import.
