### ISSUE TITLE
Fix importing Un'Goro cards from HearthPwn

### ISSUE THREAD

**Issue by ekqvist** [Freezard/hs-collection-tracker#68]
Before the patch, I could import my collection from HearthPwn with no complications. After the Un'Goro patch, I still receive the "Collection imported successfully" message while importing my collection, but no Un'Goro cards are added to the Collection Tracker site.

However, I can see all the Un'Goro cards that I own on my HearthPwn collection.

**Comment by Freezard** [comment]
Reason is the site I'm using for data lookup has not added the Un'Goro cards yet. It's kinda slow, so I might change source.

**Comment by ekqvist** [comment]
Thanks for the answer. Good to know it will work again at some point. Your site is extremely useful.
