### ISSUE TITLE
Uncollectible cards in card-ids.json

### ISSUE THREAD

**Issue by MatteoGrossele** [Freezard/hs-collection-tracker#69]
Inside the file card-ids.json ( used to gather hearthpwn ids) there are some uncollectible cards, mainly from the early sets (for example boom bots, gallywix coin, ...)

**Comment by MatteoGrossele** [comment]
I'm quite familiar with this file, I could fix this  if you say these cards can be removed and they are not there for some extra  feature. 
Also, since the attribute 'whid' is no longer obtainable because the hearthhead site changed, can this data be removed from all the cards in this file? I saw that it is never used.

**Comment by Freezard** [comment]
Hi yes, it would be good with some cleanup. Go ahead and remove whids too, they're not used, just leftovers from the original file.
