### ISSUE TITLE
Import from HearthPwn broken

### ISSUE THREAD

**Issue by Klaudi** [Freezard/hs-collection-tracker#71]
Like per title: import from HearthPwn doesn't work atm.
Username is correct and collection is set to public, I double-checked, but still get the error "Wrong username or collection set to private".
It used to work in the past but now it doesn't. Can't tell when exactly it stopped working because I hadn't use Hearthstone Collection Tracker in a while. Best estimate is some time between 3 months ago and now.
Tested on Opera 46.0 and Chrome 59.0.

**Comment by Freezard** [comment]
Yes it appears Yahoo has stopped supporting the library I'm using to import the data for no known reason. Will look into it and find another solution.
