### ISSUE TITLE
Not importing collection

### ISSUE THREAD

**Issue by Iztooi** [Freezard/hs-collection-tracker#74]
Hello,
I tried to set up my collection to public, and tried to import but:
1. It takes forever;
2. After 10 seconds the tab doesn't request any more memory/cpu
3. If I check the collection it's very weird (it has selected cards randomly).
I tried with Opera and Chrome, same result in both of them.
Do you know if something is linked to Chrome browsers, or it's another bug?

**Comment by Freezard** [comment]
Sorry there was a problem with the new KotFT data. Try it now.
