### ISSUE TITLE
Failing to import large collections from HearthPwn

### ISSUE THREAD

**Issue by Freezard** [Freezard/hs-collection-tracker#76]
HCT will fail to import large collections with golden cards due to YQL having a limit on the stream data.

**Comment by Iztooi** [comment]
Is there any news on this? Maybe a way to use something else to import a collection with golden cards?

**Comment by Freezard** [comment]
It started working for me again. Does it fail for you?

**Comment by Iztooi** [comment]
Yes i just tried, with the full collection i see the "Importing failed. Try editing and saving collection on HearthPwn again" error. 
If i edit my collection on Hearthpwn (just edit and save) it removes all the golden cards and the tracker loads my collection successfully

**Comment by Freezard** [comment]
Unfortunately there doesn't seem to be any simple solution since the website is client-side and so the options are limited. And I don't think there's any point importing from any other place than HearthPwn since that's by far the most popular place where people put their collection. It should be fixed once the site moves to a server-based version eventually.

**Comment by Freezard** [comment]
Yahoo has now shut down YQL meaning the import function won't work at all.

**Comment by Freezard** [comment]
The function now works properly, there are still issues although it's on HearthPwn's side.
