### ISSUE TITLE
I cannot import my collection from hearthpwn

### ISSUE THREAD

**Issue by XGEu2X** [Freezard/hs-collection-tracker#78]
Just that, I have set my collection public and have tried edit & save trick and nothing works.

**Comment by Freezard** [comment]
Right now there are some issues with the API being down because it's updating to the new cards so the tracker doesn't work correctly. I'll check if it works tomorrow.

**Comment by Freezard** [comment]
Tracker is updated and it should work again, if it doesn't then it's likely an issue with having too many cards in the collection: https://github.com/Freezard/hs-collection-tracker/issues/76#issue-282572255
