### ISSUE TITLE
New tooltips needed to replace HearthPwn

### ISSUE THREAD

**Issue by Freezard** [Freezard/hs-collection-tracker#82]
The app is currently using the card tooltips by HearthPwn (http://www.hearthpwn.com/tooltips), which is not supported anymore.

Need to find an alternative API.

**Comment by Bartwillemsen** [comment]
Tooltips on Hearthstone wiki still seems to work. What API do they use?

**Comment by Freezard** [comment]
They're using internal tooltip scripts and images. icy-veins too it looks like.

I did write to HearthPwn about it, since they got new owners, might be able to fix it. Otherwise I could do Bootstrap 4 tooltips but not sure how efficient that would be.

**Comment by Freezard** [comment]
Fixed with Tippy.js using card images from https://art.hearthstonejson.com/.

A bit jerky when images take too long to load, will look into it. Any other issues report them to me.
