### ISSUE TITLE
Cannot import from HSReplay

### ISSUE THREAD

**Issue by Estelyen** [Freezard/hs-collection-tracker#85]
Ever since the patch with the new pack opening system was released, I can no longer import my collection from HSReplay into the collection tracker. It just says "Importing failed. Unable to connect to card database".

I double checked that I'm still using the correct link and even cycled my collection to private and then to public again, no change.

**Comment by Freezard** [comment]
Sorry it was an issue with the new Demon Hunter being added, fixed now.
