### ISSUE TITLE
Didnt know how to contact you

### ISSUE THREAD

**Issue by mortesd** [Freezard/hs-collection-tracker#89]
Hey. I am trying to create an Arena Style webapp for my collection. I have tried to import my collection from the hsreplay collection link to your web app and then exported it to a json file. Is this now my collection? I am trying to find a way to import from HSreplay to json file, or export my collection from HSreplay to a json file. Is this something you could give me some advice on? Thank Morten

**Comment by Freezard** [comment]
Yes it's your collection, you can also import it directly from HSReplay through their API:

https://hsreplay.net/api/v1/collection/?region=X&account_lo=X

Then get the card names from api.hearthstonejson.com by matching dbfId with HSReplay JSON.

For example '"12":[2,1]' means Mana Addict 2 commons and 1 golden owned.

**Comment by mortesd** [comment]
thanks man. I will definatily play around with it. And see what i can do

**Comment by mortesd** [comment]
How about images? Is there anywhere an image attribute for the entire card? like a file path string

**Comment by Freezard** [comment]
https://hearthstonejson.com/docs/images.html

On this API the image attribute is the id of the card.

**Comment by mortesd** [comment]
Thanks a lot :)
