### ISSUE TITLE
Import from HSReplay doesn´t work

### ISSUE THREAD

**Issue by juanmacozzuol** [Freezard/hs-collection-tracker#90]
It returns "Importing failed. Unable to connect to card database"

**Comment by Freezard** [comment]
Sounds like API is temporarily down. Try again or try in incognito window.

**Comment by juanmacozzuol** [comment]
Thanks for the fast answer, and also congrats for the tracker. It´s great work

**Comment by Freezard** [comment]
And was the problem solved?

**Comment by juanmacozzuol** [comment]
No, still couldn´t, not even in incognito window

**Comment by Freezard** [comment]
Sorry it was my fault, it's fixed now.
